EPAPER_DISPLAY_WIDTH = 170.2;
EPAPER_DISPLAY_HEIGHT = 111.2;

EPAPER_DISPLAY_INNER_WIDTH = 163.2;
EPAPER_DISPLAY_INNER_HEIGHT = 97.92;

EPAPER_DISPLAY_LEFT_BORDER = (EPAPER_DISPLAY_WIDTH - EPAPER_DISPLAY_INNER_WIDTH) / 2;
EPAPER_DISPLAY_RIGHT_BORDER = EPAPER_DISPLAY_LEFT_BORDER;
EPAPER_DISPLAY_TOP_BORDER = EPAPER_DISPLAY_LEFT_BORDER;
EPAPER_DISPLAY_BOTTOM_BORDER = EPAPER_DISPLAY_HEIGHT - EPAPER_DISPLAY_INNER_HEIGHT - EPAPER_DISPLAY_TOP_BORDER;
